/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\WWW\\sms-admin-composer-git\\yihaotong-github\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0cb4d4e0",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cb4d4e0").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-71de94df",
    path: "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/API/%E9%87%87%E9%9B%86%E8%AE%B0%E5%BD%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71de94df").then(next)
    },
  },
  {
    path: "/商品采集/API/采集记录.html",
    redirect: "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/API/%E9%87%87%E9%9B%86%E8%AE%B0%E5%BD%95.html"
  },
  {
    path: "/商品采集/API/采集记录.html",
    redirect: "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/API/%E9%87%87%E9%9B%86%E8%AE%B0%E5%BD%95.html"
  },
  {
    name: "v-1c58fb57",
    path: "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c58fb57").then(next)
    },
  },
  {
    path: "/商品采集/使用说明.html",
    redirect: "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html"
  },
  {
    path: "/商品采集/使用说明.html",
    redirect: "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html"
  },
  {
    name: "v-2978bd65",
    path: "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/API/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2978bd65").then(next)
    },
  },
  {
    path: "/商品采集/API/商品采集.html",
    redirect: "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/API/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86.html"
  },
  {
    path: "/商品采集/API/商品采集.html",
    redirect: "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/API/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86.html"
  },
  {
    name: "v-26fe3081",
    path: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%88%9B%E5%BB%BA%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6%E8%AE%A2%E5%8D%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26fe3081").then(next)
    },
  },
  {
    path: "/商家寄件/API/创建商家寄件订单.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%88%9B%E5%BB%BA%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6%E8%AE%A2%E5%8D%95.html"
  },
  {
    path: "/商家寄件/API/创建商家寄件订单.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%88%9B%E5%BB%BA%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6%E8%AE%A2%E5%8D%95.html"
  },
  {
    name: "v-0e09a772",
    path: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e09a772").then(next)
    },
  },
  {
    path: "/商家寄件/使用说明.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html"
  },
  {
    path: "/商家寄件/使用说明.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html"
  },
  {
    name: "v-0c2fd430",
    path: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E8%8E%B7%E5%8F%96%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6%E5%BF%AB%E9%80%92%E5%85%AC%E5%8F%B8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c2fd430").then(next)
    },
  },
  {
    path: "/商家寄件/API/获取商家寄件快递公司.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E8%8E%B7%E5%8F%96%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6%E5%BF%AB%E9%80%92%E5%85%AC%E5%8F%B8.html"
  },
  {
    path: "/商家寄件/API/获取商家寄件快递公司.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E8%8E%B7%E5%8F%96%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6%E5%BF%AB%E9%80%92%E5%85%AC%E5%8F%B8.html"
  },
  {
    name: "v-5f6830cf",
    path: "/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/%E8%BF%94%E5%9B%9E%E8%AF%B4%E6%98%8E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f6830cf").then(next)
    },
  },
  {
    path: "/常见问题/返回说明.html",
    redirect: "/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/%E8%BF%94%E5%9B%9E%E8%AF%B4%E6%98%8E.html"
  },
  {
    path: "/常见问题/返回说明.html",
    redirect: "/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/%E8%BF%94%E5%9B%9E%E8%AF%B4%E6%98%8E.html"
  },
  {
    name: "v-7e2e335b",
    path: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%AF%84%E4%BB%B6%E8%AE%A2%E5%8D%95%E5%88%97%E8%A1%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e2e335b").then(next)
    },
  },
  {
    path: "/商家寄件/API/寄件订单列表.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%AF%84%E4%BB%B6%E8%AE%A2%E5%8D%95%E5%88%97%E8%A1%A8.html"
  },
  {
    path: "/商家寄件/API/寄件订单列表.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%AF%84%E4%BB%B6%E8%AE%A2%E5%8D%95%E5%88%97%E8%A1%A8.html"
  },
  {
    name: "v-0f147e12",
    path: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%8F%96%E6%B6%88%E5%AF%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f147e12").then(next)
    },
  },
  {
    path: "/商家寄件/API/取消寄件.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%8F%96%E6%B6%88%E5%AF%84%E4%BB%B6.html"
  },
  {
    path: "/商家寄件/API/取消寄件.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%8F%96%E6%B6%88%E5%AF%84%E4%BB%B6.html"
  },
  {
    name: "v-6426bb52",
    path: "/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6426bb52").then(next)
    },
  },
  {
    path: "/常见问题/常见错误.html",
    redirect: "/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF.html"
  },
  {
    path: "/常见问题/常见错误.html",
    redirect: "/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF.html"
  },
  {
    name: "v-41bfaed0",
    path: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E8%AE%A2%E5%8D%95%E5%9B%9E%E8%B0%83.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41bfaed0").then(next)
    },
  },
  {
    path: "/商家寄件/API/订单回调.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E8%AE%A2%E5%8D%95%E5%9B%9E%E8%B0%83.html"
  },
  {
    path: "/商家寄件/API/订单回调.html",
    redirect: "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E8%AE%A2%E5%8D%95%E5%9B%9E%E8%B0%83.html"
  },
  {
    name: "v-0c236a16",
    path: "/%E5%BA%94%E7%94%A8%E7%AE%A1%E7%90%86/%E8%8E%B7%E5%8F%96%E6%8E%88%E6%9D%83TOKEN.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c236a16").then(next)
    },
  },
  {
    path: "/应用管理/获取授权TOKEN.html",
    redirect: "/%E5%BA%94%E7%94%A8%E7%AE%A1%E7%90%86/%E8%8E%B7%E5%8F%96%E6%8E%88%E6%9D%83TOKEN.html"
  },
  {
    path: "/应用管理/获取授权TOKEN.html",
    redirect: "/%E5%BA%94%E7%94%A8%E7%AE%A1%E7%90%86/%E8%8E%B7%E5%8F%96%E6%8E%88%E6%9D%83TOKEN.html"
  },
  {
    name: "v-5fb3c9d3",
    path: "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/API%E6%A6%82%E5%86%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fb3c9d3").then(next)
    },
  },
  {
    path: "/快速入门/API概况.html",
    redirect: "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/API%E6%A6%82%E5%86%B5.html"
  },
  {
    path: "/快速入门/API概况.html",
    redirect: "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/API%E6%A6%82%E5%86%B5.html"
  },
  {
    name: "v-1884abd1",
    path: "/%E5%BA%94%E7%94%A8%E7%AE%A1%E7%90%86/APPID%E8%8E%B7%E5%8F%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1884abd1").then(next)
    },
  },
  {
    path: "/应用管理/APPID获取.html",
    redirect: "/%E5%BA%94%E7%94%A8%E7%AE%A1%E7%90%86/APPID%E8%8E%B7%E5%8F%96.html"
  },
  {
    path: "/应用管理/APPID获取.html",
    redirect: "/%E5%BA%94%E7%94%A8%E7%AE%A1%E7%90%86/APPID%E8%8E%B7%E5%8F%96.html"
  },
  {
    name: "v-6db6deff",
    path: "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6db6deff").then(next)
    },
  },
  {
    path: "/物流查询/使用说明.html",
    redirect: "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html"
  },
  {
    path: "/物流查询/使用说明.html",
    redirect: "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html"
  },
  {
    name: "v-3ff37365",
    path: "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/API/%E6%9F%A5%E8%AF%A2%E7%89%A9%E6%B5%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ff37365").then(next)
    },
  },
  {
    path: "/物流查询/API/查询物流.html",
    redirect: "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/API/%E6%9F%A5%E8%AF%A2%E7%89%A9%E6%B5%81.html"
  },
  {
    path: "/物流查询/API/查询物流.html",
    redirect: "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/API/%E6%9F%A5%E8%AF%A2%E7%89%A9%E6%B5%81.html"
  },
  {
    name: "v-4b1d6a1e",
    path: "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b1d6a1e").then(next)
    },
  },
  {
    path: "/快速入门/",
    redirect: "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/"
  },
  {
    path: "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/index.html",
    redirect: "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/"
  },
  {
    path: "/快速入门/",
    redirect: "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/"
  },
  {
    name: "v-2b32242c",
    path: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E5%8F%91%E9%80%81%E7%9F%AD%E4%BF%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b32242c").then(next)
    },
  },
  {
    path: "/短信服务/API/发送短信.html",
    redirect: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E5%8F%91%E9%80%81%E7%9F%AD%E4%BF%A1.html"
  },
  {
    path: "/短信服务/API/发送短信.html",
    redirect: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E5%8F%91%E9%80%81%E7%9F%AD%E4%BF%A1.html"
  },
  {
    name: "v-713e11da",
    path: "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/API/%E6%9F%A5%E8%AF%A2%E8%AE%B0%E5%BD%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-713e11da").then(next)
    },
  },
  {
    path: "/物流查询/API/查询记录.html",
    redirect: "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/API/%E6%9F%A5%E8%AF%A2%E8%AE%B0%E5%BD%95.html"
  },
  {
    path: "/物流查询/API/查询记录.html",
    redirect: "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/API/%E6%9F%A5%E8%AF%A2%E8%AE%B0%E5%BD%95.html"
  },
  {
    name: "v-70e97b8e",
    path: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E8%8E%B7%E5%8F%96%E7%9F%AD%E4%BF%A1%E6%A8%A1%E6%9D%BF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70e97b8e").then(next)
    },
  },
  {
    path: "/短信服务/API/获取短信模板.html",
    redirect: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E8%8E%B7%E5%8F%96%E7%9F%AD%E4%BF%A1%E6%A8%A1%E6%9D%BF.html"
  },
  {
    path: "/短信服务/API/获取短信模板.html",
    redirect: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E8%8E%B7%E5%8F%96%E7%9F%AD%E4%BF%A1%E6%A8%A1%E6%9D%BF.html"
  },
  {
    name: "v-705a516e",
    path: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-705a516e").then(next)
    },
  },
  {
    path: "/短信服务/使用说明.html",
    redirect: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html"
  },
  {
    path: "/短信服务/使用说明.html",
    redirect: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html"
  },
  {
    name: "v-68448941",
    path: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E5%8F%91%E9%80%81%E8%AE%B0%E5%BD%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68448941").then(next)
    },
  },
  {
    path: "/短信服务/API/发送记录.html",
    redirect: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E5%8F%91%E9%80%81%E8%AE%B0%E5%BD%95.html"
  },
  {
    path: "/短信服务/API/发送记录.html",
    redirect: "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E5%8F%91%E9%80%81%E8%AE%B0%E5%BD%95.html"
  },
  {
    name: "v-d17d9b44",
    path: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0%E8%AE%B0%E5%BD%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d17d9b44").then(next)
    },
  },
  {
    path: "/面单打印/API/电子面单打印记录.html",
    redirect: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0%E8%AE%B0%E5%BD%95.html"
  },
  {
    path: "/面单打印/API/电子面单打印记录.html",
    redirect: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0%E8%AE%B0%E5%BD%95.html"
  },
  {
    name: "v-6e1d271d",
    path: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e1d271d").then(next)
    },
  },
  {
    path: "/面单打印/使用说明.html",
    redirect: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html"
  },
  {
    path: "/面单打印/使用说明.html",
    redirect: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html"
  },
  {
    name: "v-62bc6de6",
    path: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E6%89%93%E5%8D%B0%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62bc6de6").then(next)
    },
  },
  {
    path: "/面单打印/API/打印电子面单.html",
    redirect: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E6%89%93%E5%8D%B0%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95.html"
  },
  {
    path: "/面单打印/API/打印电子面单.html",
    redirect: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E6%89%93%E5%8D%B0%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95.html"
  },
  {
    name: "v-e2349b64",
    path: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E8%8E%B7%E5%8F%96%E9%9D%A2%E5%8D%95%E6%A8%A1%E6%9D%BF%E5%88%97%E8%A1%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e2349b64").then(next)
    },
  },
  {
    path: "/面单打印/API/获取面单模板列表.html",
    redirect: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E8%8E%B7%E5%8F%96%E9%9D%A2%E5%8D%95%E6%A8%A1%E6%9D%BF%E5%88%97%E8%A1%A8.html"
  },
  {
    path: "/面单打印/API/获取面单模板列表.html",
    redirect: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E8%8E%B7%E5%8F%96%E9%9D%A2%E5%8D%95%E6%A8%A1%E6%9D%BF%E5%88%97%E8%A1%A8.html"
  },
  {
    name: "v-2129c50d",
    path: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E8%8E%B7%E5%8F%96%E7%89%A9%E6%B5%81%E5%88%97%E8%A1%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2129c50d").then(next)
    },
  },
  {
    path: "/面单打印/API/获取物流列表.html",
    redirect: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E8%8E%B7%E5%8F%96%E7%89%A9%E6%B5%81%E5%88%97%E8%A1%A8.html"
  },
  {
    path: "/面单打印/API/获取物流列表.html",
    redirect: "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E8%8E%B7%E5%8F%96%E7%89%A9%E6%B5%81%E5%88%97%E8%A1%A8.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]