/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "一号通",
  "description": "使用接口文档",
  "base": "/docs/",
  "headTags": [
    [
      "meta",
      {
        "name": "keywords",
        "content": "一号通"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "一号通文档",
        "tagline": "提供专业API服务，让企业商城运营更简单",
        "actionText": "快速上手 →",
        "actionLink": "/快速入门/",
        "features": [
          {
            "title": "对接简单",
            "details": "标准接口对接方便快捷，无需认证注册后就可以使用；"
          },
          {
            "title": "多种服务",
            "details": "内置多种服务包含短信服务、商家寄件服务、打字面单打印服务、物流查询服务、商品采集服务；"
          },
          {
            "title": "多应用",
            "details": "一账号多种应用满足这种服务的使用场景",
            "footer": "Copyright (c) 2016~2023 https://www.crmeb.com All rights reserved."
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0cb4d4e0",
      "path": "/",
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "采集记录",
      "frontmatter": {},
      "regularPath": "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/API/%E9%87%87%E9%9B%86%E8%AE%B0%E5%BD%95.html",
      "relativePath": "商品采集/API/采集记录.md",
      "key": "v-71de94df",
      "path": "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/API/%E9%87%87%E9%9B%86%E8%AE%B0%E5%BD%95.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data响应"
        },
        {
          "level": 3,
          "title": "",
          "slug": "list响应"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "使用说明",
      "frontmatter": {},
      "regularPath": "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
      "relativePath": "商品采集/使用说明.md",
      "key": "v-1c58fb57",
      "path": "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
      "headers": [
        {
          "level": 3,
          "title": "使用记录",
          "slug": "使用记录"
        },
        {
          "level": 3,
          "title": "提醒设置",
          "slug": "提醒设置"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "商品采集",
      "frontmatter": {},
      "regularPath": "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/API/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86.html",
      "relativePath": "商品采集/API/商品采集.md",
      "key": "v-2978bd65",
      "path": "/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86/API/%E5%95%86%E5%93%81%E9%87%87%E9%9B%86.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data数据"
        },
        {
          "level": 3,
          "title": "",
          "slug": "items数据"
        },
        {
          "level": 3,
          "title": "",
          "slug": "info数据"
        },
        {
          "level": 3,
          "title": "",
          "slug": "sku数据"
        },
        {
          "level": 3,
          "title": "",
          "slug": "value数据"
        },
        {
          "level": 3,
          "title": "",
          "slug": "header数据"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "创建商家寄件订单",
      "frontmatter": {},
      "regularPath": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%88%9B%E5%BB%BA%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6%E8%AE%A2%E5%8D%95.html",
      "relativePath": "商家寄件/API/创建商家寄件订单.md",
      "key": "v-26fe3081",
      "path": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%88%9B%E5%BB%BA%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6%E8%AE%A2%E5%8D%95.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "data响应",
          "slug": "data响应"
        },
        {
          "level": 3,
          "title": "注意事项",
          "slug": "注意事项"
        },
        {
          "level": 3,
          "title": "订单状态问题",
          "slug": "订单状态问题"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "使用说明",
      "frontmatter": {},
      "regularPath": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
      "relativePath": "商家寄件/使用说明.md",
      "key": "v-0e09a772",
      "path": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
      "headers": [
        {
          "level": 3,
          "title": "使用记录",
          "slug": "使用记录"
        },
        {
          "level": 3,
          "title": "提醒设置",
          "slug": "提醒设置"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "获取商家寄件快递公司",
      "frontmatter": {},
      "regularPath": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E8%8E%B7%E5%8F%96%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6%E5%BF%AB%E9%80%92%E5%85%AC%E5%8F%B8.html",
      "relativePath": "商家寄件/API/获取商家寄件快递公司.md",
      "key": "v-0c2fd430",
      "path": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E8%8E%B7%E5%8F%96%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6%E5%BF%AB%E9%80%92%E5%85%AC%E5%8F%B8.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data数据"
        },
        {
          "level": 3,
          "title": "",
          "slug": "list数据"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "返回说明",
      "frontmatter": {},
      "regularPath": "/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/%E8%BF%94%E5%9B%9E%E8%AF%B4%E6%98%8E.html",
      "relativePath": "常见问题/返回说明.md",
      "key": "v-5f6830cf",
      "path": "/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/%E8%BF%94%E5%9B%9E%E8%AF%B4%E6%98%8E.html",
      "headers": [
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "status错误码说明",
          "slug": "status错误码说明"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "寄件订单列表",
      "frontmatter": {},
      "regularPath": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%AF%84%E4%BB%B6%E8%AE%A2%E5%8D%95%E5%88%97%E8%A1%A8.html",
      "relativePath": "商家寄件/API/寄件订单列表.md",
      "key": "v-7e2e335b",
      "path": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%AF%84%E4%BB%B6%E8%AE%A2%E5%8D%95%E5%88%97%E8%A1%A8.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data响应"
        },
        {
          "level": 3,
          "title": "",
          "slug": "list数据"
        },
        {
          "level": 3,
          "title": "",
          "slug": "order-change数据"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "取消寄件",
      "frontmatter": {},
      "regularPath": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%8F%96%E6%B6%88%E5%AF%84%E4%BB%B6.html",
      "relativePath": "商家寄件/API/取消寄件.md",
      "key": "v-0f147e12",
      "path": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E5%8F%96%E6%B6%88%E5%AF%84%E4%BB%B6.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "常见问题",
      "frontmatter": {},
      "regularPath": "/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF.html",
      "relativePath": "常见问题/常见错误.md",
      "key": "v-6426bb52",
      "path": "/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF.html",
      "headers": [
        {
          "level": 3,
          "title": "短信服务中的短信模板审核需要多久？",
          "slug": "短信服务中的短信模板审核需要多久"
        },
        {
          "level": 3,
          "title": "AccessKey作用？",
          "slug": "accesskey作用"
        },
        {
          "level": 3,
          "title": "电子面单打印打印机购买机型？",
          "slug": "电子面单打印打印机购买机型"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "订单回调",
      "frontmatter": {},
      "regularPath": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E8%AE%A2%E5%8D%95%E5%9B%9E%E8%B0%83.html",
      "relativePath": "商家寄件/API/订单回调.md",
      "key": "v-41bfaed0",
      "path": "/%E5%95%86%E5%AE%B6%E5%AF%84%E4%BB%B6/API/%E8%AE%A2%E5%8D%95%E5%9B%9E%E8%B0%83.html",
      "headers": [
        {
          "level": 3,
          "title": "回调语法",
          "slug": "回调语法"
        },
        {
          "level": 3,
          "title": "回调头",
          "slug": "回调头"
        },
        {
          "level": 3,
          "title": "回调接口状态说明",
          "slug": "回调接口状态说明"
        },
        {
          "level": 3,
          "title": "请求元素",
          "slug": "请求元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data数据"
        },
        {
          "level": 3,
          "title": "返回元素",
          "slug": "返回元素"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "获取授权TOKEN",
      "frontmatter": {},
      "regularPath": "/%E5%BA%94%E7%94%A8%E7%AE%A1%E7%90%86/%E8%8E%B7%E5%8F%96%E6%8E%88%E6%9D%83TOKEN.html",
      "relativePath": "应用管理/获取授权TOKEN.md",
      "key": "v-0c236a16",
      "path": "/%E5%BA%94%E7%94%A8%E7%AE%A1%E7%90%86/%E8%8E%B7%E5%8F%96%E6%8E%88%E6%9D%83TOKEN.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "data响应",
          "slug": "data响应"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "API概况",
      "frontmatter": {},
      "regularPath": "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/API%E6%A6%82%E5%86%B5.html",
      "relativePath": "快速入门/API概况.md",
      "key": "v-5fb3c9d3",
      "path": "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/API%E6%A6%82%E5%86%B5.html",
      "headers": [
        {
          "level": 3,
          "title": "公共请求头",
          "slug": "公共请求头"
        },
        {
          "level": 3,
          "title": "关于短信服务API",
          "slug": "关于短信服务api"
        },
        {
          "level": 3,
          "title": "关于商家寄件服务API",
          "slug": "关于商家寄件服务api"
        },
        {
          "level": 3,
          "title": "关于面单打印服务API",
          "slug": "关于面单打印服务api"
        },
        {
          "level": 3,
          "title": "关于物流查询API",
          "slug": "关于物流查询api"
        },
        {
          "level": 3,
          "title": "关于商品采集API",
          "slug": "关于商品采集api"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "APPID获取",
      "frontmatter": {},
      "regularPath": "/%E5%BA%94%E7%94%A8%E7%AE%A1%E7%90%86/APPID%E8%8E%B7%E5%8F%96.html",
      "relativePath": "应用管理/APPID获取.md",
      "key": "v-1884abd1",
      "path": "/%E5%BA%94%E7%94%A8%E7%AE%A1%E7%90%86/APPID%E8%8E%B7%E5%8F%96.html",
      "headers": [
        {
          "level": 3,
          "title": "获取APPID和AppSecret",
          "slug": "获取appid和appsecret"
        },
        {
          "level": 3,
          "title": "APPID的作用",
          "slug": "appid的作用"
        },
        {
          "level": 3,
          "title": "关联签名",
          "slug": "关联签名"
        },
        {
          "level": 3,
          "title": "应用列表",
          "slug": "应用列表"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "使用说明",
      "frontmatter": {},
      "regularPath": "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
      "relativePath": "物流查询/使用说明.md",
      "key": "v-6db6deff",
      "path": "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
      "headers": [
        {
          "level": 3,
          "title": "使用记录",
          "slug": "使用记录"
        },
        {
          "level": 3,
          "title": "提醒设置",
          "slug": "提醒设置"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "查询物流",
      "frontmatter": {},
      "regularPath": "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/API/%E6%9F%A5%E8%AF%A2%E7%89%A9%E6%B5%81.html",
      "relativePath": "物流查询/API/查询物流.md",
      "key": "v-3ff37365",
      "path": "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/API/%E6%9F%A5%E8%AF%A2%E7%89%A9%E6%B5%81.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "data响应",
          "slug": "data响应"
        },
        {
          "level": 3,
          "title": "",
          "slug": "content响应"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "快速入门",
      "frontmatter": {},
      "regularPath": "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/",
      "relativePath": "快速入门/index.md",
      "key": "v-4b1d6a1e",
      "path": "/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/",
      "headers": [
        {
          "level": 3,
          "title": "请求地址",
          "slug": "请求地址"
        },
        {
          "level": 3,
          "title": "接口并发",
          "slug": "接口并发"
        },
        {
          "level": 3,
          "title": "使用说明",
          "slug": "使用说明"
        },
        {
          "level": 3,
          "title": "一号通定价",
          "slug": "一号通定价"
        },
        {
          "level": 3,
          "title": "资源术语",
          "slug": "资源术语"
        },
        {
          "level": 3,
          "title": "旧版本和v2新版区别",
          "slug": "旧版本和v2新版区别"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "发送短信",
      "frontmatter": {},
      "regularPath": "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E5%8F%91%E9%80%81%E7%9F%AD%E4%BF%A1.html",
      "relativePath": "短信服务/API/发送短信.md",
      "key": "v-2b32242c",
      "path": "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E5%8F%91%E9%80%81%E7%9F%AD%E4%BF%A1.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "data响应",
          "slug": "data响应"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "查询记录",
      "frontmatter": {},
      "regularPath": "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/API/%E6%9F%A5%E8%AF%A2%E8%AE%B0%E5%BD%95.html",
      "relativePath": "物流查询/API/查询记录.md",
      "key": "v-713e11da",
      "path": "/%E7%89%A9%E6%B5%81%E6%9F%A5%E8%AF%A2/API/%E6%9F%A5%E8%AF%A2%E8%AE%B0%E5%BD%95.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data响应"
        },
        {
          "level": 3,
          "title": "",
          "slug": "list响应"
        },
        {
          "level": 3,
          "title": "",
          "slug": "content-content响应"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "获取短信模板",
      "frontmatter": {},
      "regularPath": "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E8%8E%B7%E5%8F%96%E7%9F%AD%E4%BF%A1%E6%A8%A1%E6%9D%BF.html",
      "relativePath": "短信服务/API/获取短信模板.md",
      "key": "v-70e97b8e",
      "path": "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E8%8E%B7%E5%8F%96%E7%9F%AD%E4%BF%A1%E6%A8%A1%E6%9D%BF.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data响应"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data数据"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "使用说明",
      "frontmatter": {},
      "regularPath": "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
      "relativePath": "短信服务/使用说明.md",
      "key": "v-705a516e",
      "path": "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
      "headers": [
        {
          "level": 3,
          "title": "短信用量说明",
          "slug": "短信用量说明"
        },
        {
          "level": 3,
          "title": "签名管理",
          "slug": "签名管理"
        },
        {
          "level": 3,
          "title": "使用记录",
          "slug": "使用记录"
        },
        {
          "level": 3,
          "title": "短信模板",
          "slug": "短信模板"
        },
        {
          "level": 3,
          "title": "消息提醒",
          "slug": "消息提醒"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "发送记录",
      "frontmatter": {},
      "regularPath": "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E5%8F%91%E9%80%81%E8%AE%B0%E5%BD%95.html",
      "relativePath": "短信服务/API/发送记录.md",
      "key": "v-68448941",
      "path": "/%E7%9F%AD%E4%BF%A1%E6%9C%8D%E5%8A%A1/API/%E5%8F%91%E9%80%81%E8%AE%B0%E5%BD%95.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data响应"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data数据"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "电子面单打印记录",
      "frontmatter": {},
      "regularPath": "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0%E8%AE%B0%E5%BD%95.html",
      "relativePath": "面单打印/API/电子面单打印记录.md",
      "key": "v-d17d9b44",
      "path": "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0%E8%AE%B0%E5%BD%95.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data响应"
        },
        {
          "level": 3,
          "title": "",
          "slug": "list响应"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "使用说明",
      "frontmatter": {},
      "regularPath": "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
      "relativePath": "面单打印/使用说明.md",
      "key": "v-6e1d271d",
      "path": "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html",
      "headers": [
        {
          "level": 3,
          "title": "使用记录",
          "slug": "使用记录"
        },
        {
          "level": 3,
          "title": "提醒设置",
          "slug": "提醒设置"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "打印电子面单",
      "frontmatter": {},
      "regularPath": "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E6%89%93%E5%8D%B0%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95.html",
      "relativePath": "面单打印/API/打印电子面单.md",
      "key": "v-62bc6de6",
      "path": "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E6%89%93%E5%8D%B0%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "data响应（主要关注以下字段信息）",
          "slug": "data响应-主要关注以下字段信息"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "获取面单模板列表",
      "frontmatter": {},
      "regularPath": "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E8%8E%B7%E5%8F%96%E9%9D%A2%E5%8D%95%E6%A8%A1%E6%9D%BF%E5%88%97%E8%A1%A8.html",
      "relativePath": "面单打印/API/获取面单模板列表.md",
      "key": "v-e2349b64",
      "path": "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E8%8E%B7%E5%8F%96%E9%9D%A2%E5%8D%95%E6%A8%A1%E6%9D%BF%E5%88%97%E8%A1%A8.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data响应"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data响应-2"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    },
    {
      "title": "获取物流列表",
      "frontmatter": {},
      "regularPath": "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E8%8E%B7%E5%8F%96%E7%89%A9%E6%B5%81%E5%88%97%E8%A1%A8.html",
      "relativePath": "面单打印/API/获取物流列表.md",
      "key": "v-2129c50d",
      "path": "/%E9%9D%A2%E5%8D%95%E6%89%93%E5%8D%B0/API/%E8%8E%B7%E5%8F%96%E7%89%A9%E6%B5%81%E5%88%97%E8%A1%A8.html",
      "headers": [
        {
          "level": 3,
          "title": "请求语法",
          "slug": "请求语法"
        },
        {
          "level": 3,
          "title": "请求头",
          "slug": "请求头"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应元素",
          "slug": "响应元素"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data响应"
        },
        {
          "level": 3,
          "title": "",
          "slug": "data响应-2"
        }
      ],
      "lastUpdated": "7/25/2023, 2:07:34 PM",
      "lastUpdatedTimestamp": 1690265254000
    }
  ],
  "themeConfig": {
    "smoothScroll": true,
    "lastUpdated": "更新时间",
    "repo": "https://gitee.com/ZhongBangKeJi/yihaotong.git",
    "editLinkText": "帮助我们改善此页面！",
    "docsBranch": "master",
    "editLinks": true,
    "docsDir": "docs",
    "sidebar": [
      {
        "title": "快速入门",
        "collapsable": false,
        "children": [
          "/快速入门/",
          "/快速入门/API概况",
          "/应用管理/APPID获取",
          "/应用管理/获取授权TOKEN"
        ]
      },
      {
        "title": "短信服务",
        "collapsable": false,
        "children": [
          "/短信服务/使用说明",
          {
            "title": "API",
            "collapsable": false,
            "children": [
              "/短信服务/API/发送短信",
              "/短信服务/API/获取短信模板",
              "/短信服务/API/发送记录"
            ]
          }
        ]
      },
      {
        "title": "商家寄件",
        "collapsable": false,
        "children": [
          "/商家寄件/使用说明",
          {
            "title": "API",
            "collapsable": false,
            "children": [
              "/商家寄件/API/创建商家寄件订单",
              "/商家寄件/API/取消寄件",
              "/商家寄件/API/寄件订单列表",
              "/商家寄件/API/获取商家寄件快递公司",
              "/商家寄件/API/订单回调"
            ]
          }
        ]
      },
      {
        "title": "面单打印",
        "collapsable": false,
        "children": [
          "/面单打印/使用说明",
          {
            "title": "API",
            "collapsable": false,
            "children": [
              "/面单打印/API/打印电子面单",
              "/面单打印/API/获取物流列表",
              "/面单打印/API/获取面单模板列表",
              "/面单打印/API/电子面单打印记录"
            ]
          }
        ]
      },
      {
        "title": "物流查询",
        "collapsable": false,
        "children": [
          "/物流查询/使用说明",
          {
            "title": "API",
            "collapsable": false,
            "children": [
              "/物流查询/API/查询物流",
              "/物流查询/API/查询记录"
            ]
          }
        ]
      },
      {
        "title": "商品采集",
        "collapsable": false,
        "children": [
          "/商品采集/使用说明",
          {
            "title": "API",
            "collapsable": false,
            "children": [
              "/商品采集/API/商品采集",
              "/商品采集/API/采集记录"
            ]
          }
        ]
      },
      {
        "title": "常见问题",
        "collapsable": false,
        "children": [
          "/常见问题/返回说明",
          "/常见问题/常见错误"
        ]
      }
    ],
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "一号通工作台",
        "link": "https://api.crmeb.com",
        "target": "_blank"
      }
    ]
  }
}